include:
  - path: backend/docker-compose.yml

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: dev
    environment:
      VITE_BACKEND_URL: http://api:8000
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/packages/api/node_modules
      - /app/packages/app/node_modules
      - /app/packages/ui/node_modules
      - /app/packages/features/node_modules
