"""add cluster_run_stage fix calculated_at

Revision ID: 516341f83e32
Revises: e1f3a5c7b9d2
Create Date: 2026-06-02 04:35:31.640991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '516341f83e32'
down_revision: Union[str, None] = 'e1f3a5c7b9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_run_stage',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('cluster', 'score', 'label', 'prune', name='pipelinestage'), nullable=False),
    sa.Column('status', sa.Enum('running', 'done', 'failed', name='stagestatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['cluster_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'stage', name='uq_cluster_run_stage_run_stage')
    )
    op.create_index('ix_cluster_run_stage_run_id', 'cluster_run_stage', ['run_id'], unique=False)
    op.alter_column(
        'cluster_insight',
        'calculated_at',
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        nullable=True,
        existing_server_default=sa.text('now()'),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'cluster_insight',
        'calculated_at',
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text('now()'),
        nullable=False,
        existing_nullable=True,
    )
    op.drop_index('ix_cluster_run_stage_run_id', table_name='cluster_run_stage')
    op.drop_table('cluster_run_stage')
    op.execute("DROP TYPE IF EXISTS pipelinestage")
    op.execute("DROP TYPE IF EXISTS stagestatus")
    # ### end Alembic commands ###
