"""add_pipeline_group_lock

Revision ID: 5c201ef892c5
Revises: ba20901f2d9c
Create Date: 2026-05-02 15:33:33.166396

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "5c201ef892c5"
down_revision: Union[str, None] = "ba20901f2d9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipeline_group_lock",
        sa.Column("group_name", sa.String(), nullable=False),
        sa.Column("locked_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("group_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pipeline_group_lock")
    # ### end Alembic commands ###
