"""pr3_demand_performance_quadrant

Revision ID: 6e62c85f88ee
Revises: 516341f83e32
Create Date: 2026-06-03 11:55:25.884041

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "6e62c85f88ee"
down_revision: Union[str, None] = "516341f83e32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cluster_insight",
        sa.Column("gsc_impressions", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column(
        "cluster_insight",
        sa.Column("gsc_clicks", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column("cluster_insight", sa.Column("gsc_ctr", sa.Float(), nullable=True))
    op.add_column("cluster_insight", sa.Column("gsc_avg_position", sa.Float(), nullable=True))
    op.add_column("cluster_insight", sa.Column("demand_score", sa.Float(), nullable=True))
    op.add_column("cluster_insight", sa.Column("high_demand", sa.Boolean(), nullable=True))
    op.add_column("cluster_insight", sa.Column("performance_level", sa.String(), nullable=True))
    op.add_column("cluster_insight", sa.Column("editorial_quadrant", sa.String(), nullable=True))
    op.drop_column("cluster_insight", "gsc_demand_gap")
    op.drop_column("cluster_insight", "tempo_gsc_impressions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cluster_insight",
        sa.Column(
            "tempo_gsc_impressions",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "cluster_insight",
        sa.Column(
            "gsc_demand_gap",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("cluster_insight", "editorial_quadrant")
    op.drop_column("cluster_insight", "performance_level")
    op.drop_column("cluster_insight", "high_demand")
    op.drop_column("cluster_insight", "demand_score")
    op.drop_column("cluster_insight", "gsc_avg_position")
    op.drop_column("cluster_insight", "gsc_ctr")
    op.drop_column("cluster_insight", "gsc_clicks")
    op.drop_column("cluster_insight", "gsc_impressions")
    # ### end Alembic commands ###
