"""add_gsc_tables

Revision ID: 81927e488955
Revises: e8f3a2b91c4d
Create Date: 2026-05-07 11:39:42.280083

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "81927e488955"
down_revision: Union[str, None] = "e8f3a2b91c4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gsc_page",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("page_url", sa.String(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=True),
        sa.Column("impressions", sa.Integer(), nullable=True),
        sa.Column("ctr", sa.Float(), nullable=True),
        sa.Column("avg_position", sa.Float(), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "page_url", "period_start", "period_end", name="uq_gsc_page_url_period"
        ),
    )
    op.create_index("ix_gsc_page_period_start", "gsc_page", ["period_start"], unique=False)
    op.create_table(
        "gsc_page_query",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("page_url", sa.String(), nullable=False),
        sa.Column("query", sa.String(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=True),
        sa.Column("impressions", sa.Integer(), nullable=True),
        sa.Column("ctr", sa.Float(), nullable=True),
        sa.Column("avg_position", sa.Float(), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "page_url", "query", "period_start", "period_end", name="uq_gsc_page_query_period"
        ),
    )
    op.create_index("ix_gsc_page_query_page_url", "gsc_page_query", ["page_url"], unique=False)
    op.create_index(
        "ix_gsc_page_query_period_start", "gsc_page_query", ["period_start"], unique=False
    )
    op.create_table(
        "gsc_query",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("query", sa.String(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=True),
        sa.Column("impressions", sa.Integer(), nullable=True),
        sa.Column("ctr", sa.Float(), nullable=True),
        sa.Column("avg_position", sa.Float(), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("query", "period_start", "period_end", name="uq_gsc_query_period"),
    )
    op.create_index("ix_gsc_query_period_start", "gsc_query", ["period_start"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_gsc_query_period_start", table_name="gsc_query")
    op.drop_table("gsc_query")
    op.drop_index("ix_gsc_page_query_period_start", table_name="gsc_page_query")
    op.drop_index("ix_gsc_page_query_page_url", table_name="gsc_page_query")
    op.drop_table("gsc_page_query")
    op.drop_index("ix_gsc_page_period_start", table_name="gsc_page")
    op.drop_table("gsc_page")
    # ### end Alembic commands ###
