"""add cluster_insight desk_category user_need_category

Revision ID: b9e902e95bd6
Revises: 6e62c85f88ee
Create Date: 2026-06-29 08:26:30.286745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b9e902e95bd6'
down_revision: Union[str, None] = '6e62c85f88ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cluster_insight', sa.Column('desk_category', sa.String(), nullable=True))
    op.add_column('cluster_insight', sa.Column('user_need_category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cluster_insight', 'user_need_category')
    op.drop_column('cluster_insight', 'desk_category')
    # ### end Alembic commands ###
