"""baseline schema

Revision ID: ba20901f2d9c
Revises:
Create Date: 2026-04-30 10:29:14.536386

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

revision: str = "ba20901f2d9c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cluster_run",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "algorithm", sa.Enum("hdbscan", "kmeans", name="clusteralgorithm"), nullable=True
        ),
        sa.Column("algorithm_version", sa.String(), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "content_source",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("source_type", sa.Enum("rss", "internal", name="sourcetype"), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "status", sa.Enum("active", "error", "blocked", name="sourcestatus"), nullable=True
        ),
        sa.Column("last_fetched_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_table(
        "trend_signal",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("keyword", sa.String(), nullable=False),
        sa.Column("interest_score", sa.Float(), nullable=True),
        sa.Column("region", sa.String(), server_default="ID", nullable=False),
        sa.Column("captured_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("keyword", "captured_at", name="uq_trend_signal_keyword_captured_at"),
    )
    op.create_index("ix_trend_signal_captured_at", "trend_signal", ["captured_at"], unique=False)
    op.create_table(
        "article",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("first_paragraph", sa.Text(), nullable=True),
        sa.Column("last_paragraph", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["content_source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index("ix_article_published_at", "article", ["published_at"], unique=False)
    op.create_index("ix_article_source_id", "article", ["source_id"], unique=False)
    op.create_table(
        "article_cluster",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("centroid", Vector(768), nullable=True),
        sa.Column("member_count", sa.Integer(), nullable=True),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["cluster_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_article_cluster_is_current", "article_cluster", ["is_current"], unique=False
    )
    op.create_index("ix_article_cluster_run_id", "article_cluster", ["run_id"], unique=False)
    op.create_table(
        "article_cluster_member",
        sa.Column("cluster_id", sa.UUID(), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("relevance_score", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["article.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["article_cluster.id"],
        ),
        sa.PrimaryKeyConstraint("cluster_id", "article_id"),
    )
    op.create_index(
        "ix_article_cluster_member_article_id",
        "article_cluster_member",
        ["article_id"],
        unique=False,
    )
    op.create_table(
        "article_embedding",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("model_name", sa.String(), nullable=False),
        sa.Column("model_version", sa.String(), nullable=True),
        sa.Column("embedding", Vector(768), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["article.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("article_id"),
    )
    op.create_table(
        "article_gsc_metric",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=True),
        sa.Column("impressions", sa.Integer(), nullable=True),
        sa.Column("ctr", sa.Float(), nullable=True),
        sa.Column("avg_position", sa.Float(), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["article.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "article_id", "period_start", "period_end", name="uq_gsc_metric_article_period"
        ),
    )
    op.create_table(
        "cluster_insight",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("cluster_id", sa.UUID(), nullable=False),
        sa.Column("trend_velocity", sa.Float(), nullable=True),
        sa.Column("novelty_score", sa.Float(), nullable=True),
        sa.Column("coverage_score", sa.Float(), nullable=True),
        sa.Column(
            "recommendation",
            sa.Enum("trending", "worth_writing", "saturated", name="insightrecommendation"),
            nullable=True,
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("calculated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["article_cluster.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cluster_id"),
    )
    op.create_table(
        "trend_signal_article",
        sa.Column("trend_signal_id", sa.UUID(), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["article.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trend_signal_id"],
            ["trend_signal.id"],
        ),
        sa.PrimaryKeyConstraint("trend_signal_id", "article_id"),
    )
    op.create_index(
        "ix_trend_signal_article_article_id", "trend_signal_article", ["article_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_trend_signal_article_article_id", table_name="trend_signal_article")
    op.drop_table("trend_signal_article")
    op.drop_table("cluster_insight")
    op.drop_table("article_gsc_metric")
    op.drop_table("article_embedding")
    op.drop_index("ix_article_cluster_member_article_id", table_name="article_cluster_member")
    op.drop_table("article_cluster_member")
    op.drop_index("ix_article_cluster_run_id", table_name="article_cluster")
    op.drop_index("ix_article_cluster_is_current", table_name="article_cluster")
    op.drop_table("article_cluster")
    op.drop_index("ix_article_source_id", table_name="article")
    op.drop_index("ix_article_published_at", table_name="article")
    op.drop_table("article")
    op.drop_index("ix_trend_signal_captured_at", table_name="trend_signal")
    op.drop_table("trend_signal")
    op.drop_table("content_source")
    op.drop_table("cluster_run")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS clusteralgorithm")
    op.execute("DROP TYPE IF EXISTS sourcetype")
    op.execute("DROP TYPE IF EXISTS sourcestatus")
    op.execute("DROP TYPE IF EXISTS insightrecommendation")
