"""add_full_text_scraping

Revision ID: d5057fd81f8b
Revises: 81927e488955
Create Date: 2026-05-07 11:43:35.765180

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "d5057fd81f8b"
down_revision: Union[str, None] = "81927e488955"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE scrapestatus AS ENUM "
        "('pending', 'fast_ok', 'fast_failed', 'playwright_ok', 'playwright_failed')"
    )
    op.add_column("article", sa.Column("content", sa.Text(), nullable=True))
    op.add_column(
        "article",
        sa.Column(
            "scrape_status",
            sa.Enum(
                "pending",
                "fast_ok",
                "fast_failed",
                "playwright_ok",
                "playwright_failed",
                name="scrapestatus",
                create_type=False,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "article",
        sa.Column("scrape_attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.create_index("ix_article_scrape_status", "article", ["scrape_status"], unique=False)
    op.drop_column("article", "last_paragraph")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "article", sa.Column("last_paragraph", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_index("ix_article_scrape_status", table_name="article")
    op.drop_column("article", "scrape_attempts")
    op.drop_column("article", "scrape_status")
    op.drop_column("article", "content")
    op.execute("DROP TYPE scrapestatus")
    # ### end Alembic commands ###
