"""add cluster user_need distribution

Revision ID: e7b8b8e7783a
Revises: b9e902e95bd6
Create Date: 2026-06-30 10:46:23.749347

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "e7b8b8e7783a"
down_revision: Union[str, None] = "b9e902e95bd6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cluster_insight",
        sa.Column("user_need_distribution", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "cluster_insight", sa.Column("user_need_reps_tagged", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cluster_insight", "user_need_reps_tagged")
    op.drop_column("cluster_insight", "user_need_distribution")
    # ### end Alembic commands ###
