/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Articles */
        get: operations["list_articles_api_v1_articles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/morning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Morning Clusters */
        get: operations["morning_clusters_api_v1_clusters_morning_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/deferred": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deferred Clusters */
        get: operations["deferred_clusters_api_v1_clusters_deferred_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/runs/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Cluster Run */
        get: operations["latest_cluster_run_api_v1_clusters_runs_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Clusters */
        get: operations["current_clusters_api_v1_clusters_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{cluster_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cluster Detail */
        get: operations["cluster_detail_api_v1_clusters__cluster_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pipeline/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pipeline group lock state */
        get: operations["pipeline_status_api_v1_pipeline_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pipeline/cluster-label-score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manually trigger cluster + label + score */
        post: operations["trigger_cluster_label_score_api_v1_pipeline_cluster_label_score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pipeline/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manually trigger analysis (per-article LLM claim extraction) */
        post: operations["trigger_analysis_api_v1_pipeline_analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_v1_sources_get"];
        put?: never;
        /** Create Source */
        post: operations["create_source_api_v1_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Source */
        delete: operations["delete_source_api_v1_sources__source_id__delete"];
        options?: never;
        head?: never;
        /** Patch Source */
        patch: operations["patch_source_api_v1_sources__source_id__patch"];
        trace?: never;
    };
    "/api/v1/trend-signals/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Trend Signals */
        get: operations["latest_trend_signals_api_v1_trend_signals_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArticleResponse */
        ArticleResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** First Paragraph */
            first_paragraph: string | null;
            /** Published At */
            published_at: string | null;
            /** Created At */
            created_at: string;
            /** Source Name */
            source_name: string;
            /** Source Type */
            source_type: string;
        };
        /** ArticleSummary */
        ArticleSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** First Paragraph */
            first_paragraph: string | null;
            /** Published At */
            published_at: string | null;
            /** Source Name */
            source_name: string;
            /** Relevance Score */
            relevance_score: number | null;
        };
        /** ClusterDetail */
        ClusterDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string | null;
            /** Member Count */
            member_count: number | null;
            /** Is Current */
            is_current: boolean;
            /** Created At */
            created_at: string;
            /** Trend Velocity */
            trend_velocity: number | null;
            /** Competitor Count */
            competitor_count: number | null;
            /** Trend Match Count */
            trend_match_count: number | null;
            /** Tempo Covered */
            tempo_covered: boolean | null;
            /** Last Internal Days Ago */
            last_internal_days_ago: number | null;
            /** Underperformed */
            underperformed: boolean | null;
            /** Summary */
            summary: string[] | null;
            /** Insight Calculated At */
            insight_calculated_at: string | null;
            /** Members */
            members: components["schemas"]["ArticleSummary"][];
        };
        /** ClusterRunResponse */
        ClusterRunResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Algorithm */
            algorithm: string | null;
            /** Algorithm Version */
            algorithm_version: string | null;
            /** Params */
            params: {
                [key: string]: unknown;
            } | null;
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Notes */
            notes: string | null;
            /** Cluster Count */
            cluster_count: number;
        };
        /** ClusterSummary */
        ClusterSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string | null;
            /** Member Count */
            member_count: number | null;
            /** Is Current */
            is_current: boolean;
            /** Created At */
            created_at: string;
            /** Trend Velocity */
            trend_velocity: number | null;
            /** Competitor Count */
            competitor_count: number | null;
            /** Trend Match Count */
            trend_match_count: number | null;
            /** Tempo Covered */
            tempo_covered: boolean | null;
            /** Last Internal Days Ago */
            last_internal_days_ago: number | null;
            /** Underperformed */
            underperformed: boolean | null;
            /** Summary */
            summary: string[] | null;
            /** Insight Calculated At */
            insight_calculated_at: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PaginatedArticles */
        PaginatedArticles: {
            /** Items */
            items: components["schemas"]["ArticleResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Pages */
            total_pages: number;
        };
        /** PipelineStatusResponse */
        PipelineStatusResponse: {
            /** Cluster Label Score */
            cluster_label_score: string | null;
            /** Analysis */
            analysis: string | null;
        };
        /** PipelineTriggerResult */
        PipelineTriggerResult: {
            /** Group */
            group: string;
            /** Channel */
            channel: string;
            /** Notified */
            notified: boolean;
        };
        /** SourceCreate */
        SourceCreate: {
            /**
             * Url
             * Format: uri
             */
            url: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Is Enabled
             * @default true
             */
            is_enabled: boolean;
        };
        /** SourcePatch */
        SourcePatch: {
            /** Is Enabled */
            is_enabled?: boolean | null;
            /** Name */
            name?: string | null;
            /** Url */
            url?: string | null;
            source_type?: components["schemas"]["SourceType"] | null;
        };
        /** SourceResponse */
        SourceResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Url */
            url: string;
            /** Source Type */
            source_type: string;
            /** Is Enabled */
            is_enabled: boolean;
            /** Status */
            status: string | null;
            /** Last Fetched At */
            last_fetched_at: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Article Count 24H */
            article_count_24h: number;
        };
        /**
         * SourceType
         * @enum {string}
         */
        SourceType: "rss" | "internal";
        /** TrendSignalOut */
        TrendSignalOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Keyword */
            keyword: string;
            /** Interest Score */
            interest_score: number | null;
            /** Captured At */
            captured_at: string;
            /** Article Count */
            article_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_articles_api_v1_articles_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedArticles"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    morning_clusters_api_v1_clusters_morning_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterSummary"][];
                };
            };
        };
    };
    deferred_clusters_api_v1_clusters_deferred_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterSummary"][];
                };
            };
        };
    };
    latest_cluster_run_api_v1_clusters_runs_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterRunResponse"];
                };
            };
        };
    };
    current_clusters_api_v1_clusters_current_get: {
        parameters: {
            query?: {
                order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cluster_detail_api_v1_clusters__cluster_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cluster_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    pipeline_status_api_v1_pipeline_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineStatusResponse"];
                };
            };
        };
    };
    trigger_cluster_label_score_api_v1_pipeline_cluster_label_score_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineTriggerResult"];
                };
            };
        };
    };
    trigger_analysis_api_v1_pipeline_analysis_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineTriggerResult"];
                };
            };
        };
    };
    list_sources_api_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"][];
                };
            };
        };
    };
    create_source_api_v1_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_source_api_v1_sources__source_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_source_api_v1_sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourcePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_trend_signals_api_v1_trend_signals_latest_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendSignalOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
