// AUTO-GENERATED by `bun run gen:api`. Do not edit by hand.
// Source: backend FastAPI /openapi.json.
// Output of openapi-typescript. Committed per decisions.md D16.
// On regeneration, review diff in PR alongside Zod schema updates in schemas.ts.
