# Pydantic Settings loaded from .env via pydantic-settings.
# Exposes: DATABASE_URL, EMBEDDING_MODEL_NAME, LLM_MODEL_NAME, LOG_LEVEL,
# CLUSTERING_WINDOW_DAYS, HDBSCAN_MIN_CLUSTER_SIZE, UMAP_RANDOM_STATE, TIMEZONE.
